### ISSUE TITLE
Premissa do jogo

### ISSUE THREAD

**Issue by anne2104** [lotus-gamess/Em-busca-das-flores-magicas#1]
O reino está em apuros! Durante o baile de máscaras anual do castelo alguém envenenou a princesa Charlotte, a filha mais velha do rei Thomaz e que em breve será sucessora do trono! Agora você tem uma missão: o rei precisa que você entre na floresta e ache as flores mágicas, a única salvação de sua filha! Mas corra, você precisa acender as três flores ou a princesa morre.

**Comment by nicolysousaa** [comment]
Feita a premissa do jogo no arquivo README
