### ISSUE TITLE
O jogo ideal

### ISSUE THREAD

**Issue by nicolysousaa** [lotus-gamess/Em-busca-das-flores-magicas#7]
O jogo “Em busca das flores mágicas" é caracterizado com diversos desafios encontrados em cada uma das três fases. Maia e Ivy recebem a missão de superar uma série de obstáculos e chegar ao final do mapa com todas as flores. O jogo tem um objetivo simples, o cenário se desenvolve na floresta e os personagens precisam buscar todas as flores sem que caiam em nenhuma armadilha. Para vencer, eles precisam confiar um no outro. O jogo será lançado com um nível, que foi dividido em três fases, cada fase com um grau de dificuldade diferente.

**Comment by anne2104** [comment]
Feito o jogo ideal no arquivo README.
